config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, only: [:session, :registration]

  devise_scope :user do
    get 'admin/login', to: 'devise/sessions#new'
    authenticated :user do
      root :to => 'checkroot#index'
    end
    unauthenticated :user do
      root :to => 'posts#index'
    end
  end

  #public
  resources :posts, only:[:index, :show] do
    collection do
      get :archive
    end
  end

  #admin
  namespace :admin do
    resources :posts
    resources :payments
  end
  resources :admin, only:[:index]

  namespace :manage do
    resources :glorifies
    resources :listings
    resources :charges, only: [:create]
  end
  resources :manage, only:[:index]




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/glorify.rb
class Glorify < ApplicationRecord

  belongs_to :user
  belongs_to :post
  has_many :payment_transactions

  accepts_nested_attributes_for :payment_transactions

end

app/models/payment_transaction.rb
class PaymentTransaction < ApplicationRecord

  belongs_to :user, foreign_key: :influencer_id
  belongs_to :glorify, optional: true

  scope :pending_payment, (lambda do
    where(paid: false)
  end)

  scope :paid_payment, (lambda do
    where(paid: true)
  end)

  scope :total_amount , (lambda do
    self.sum('payment_transactions.amount')
  end)

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :glorifies

  mount_uploader :image, FeaturedImageUploader

  validates :image, :presence => true
  validates :title, :presence => true
  validates :contents, :presence => true

  scope :publish_on, (lambda do
    where("other_details -> 'is_published' ? :status", status: 'on')
  end)

  scope :publish_off, (lambda do
    where("other_details -> 'is_published' ? :status ", status: 'off')
  end)


  def self.order_recent
    self.order("created_at DESC")
  end

  def display_post_date
    self.date_format("%d %b, %Y")
  end

  def common_post_date
    self.date_format("%Y-%m-%d")
  end

  def date_format(format)
    return self.try(:created_at).strftime(format)
  end

  def image_name
    if self.image.present?
      self.image.file.identifier
    end
  end

  def is_published
    other_details["is_published"] || "off"
  end

  def update_is_published( status)
    other_details["is_published"] = status
    save
  end

  def total_count
    self.glorifies.count
  end

  def total_glorified_amount
    total = self.glorifies.sum('glorifies.amount')
    "#{total}$"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :glorifies
  has_many :glorify_posts, :through => :glorifies, :source => :post

  has_many :payments, class_name: :PaymentTransaction, foreign_key: :influencer_id

  belongs_to :post

  enum user_type: { glorifier: 0, influencer: 1, master: 4}

  def glorifier?
    self.user_type == "glorifier"
  end

  def influencer?
    self.user_type == "influencer"
  end

  def total_pending_payment_amount
    total = self.payments.pending_payment.total_amount
  end

  def total_paid_payment_amount
    total = self.payments.paid_payment.total_amount
  end


end

app/controllers/admin/payments_controller.rb
class Admin::PaymentsController < AdminController

  def index
    @available_amount = current_user.total_pending_payment_amount
    @paid_amount = current_user.total_paid_payment_amount
  end

  def create
  end

  private

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController

  def index
    @posts = current_user.posts.order_recent
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.other_details[:is_published] = "on"
    @post.other_details[:create_by] = current_user.username

    if @post.save
      flash[:success] = "Successfully Created."
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def edit
    post_info
  end

  def update
    if post_info.update_attributes(post_params.except("other_details"))

       is_published = post_params["other_details"]["is_published"]
       post_info.update_is_published( is_published )
       redirect_to edit_admin_post_path(post_info), notice: "Successfully Updated."

    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit!
  end

  def post_id
    params[:id]
  end

  def post_info
    @post = current_user.posts.find( post_id )
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!
  layout "application_admin"

  def index
    redirect_to admin_posts_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:username, :email, :user_type]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

end

app/controllers/checkroot_controller.rb
class CheckrootController < ApplicationController

  before_filter :authenticate_user!

  def index
    redirect_to path_finder
  end

  private

  def path_finder
    if current_user.glorifier?
      Rails.logger.info "Glorifier"
      manage_glorifies_path
    elsif current_user.influencer?
      Rails.logger.info "influencer"
      admin_posts_path
    else
      posts_path
    end
  end

end

app/controllers/manage_controller.rb
class ManageController < ApplicationController

  before_action :authenticate_user!
  layout "application_buyer"

  def index
    redirect_to manage_glories_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    posts = Post.order_recent
    @posts = posts.limit(5)
    @post_count = posts.count
  end

  def archive
    @posts = Post.order_recent.page(page_param).per(5)
  end

  def show
    @post = Post.find(post_id)
  end

  private

  def post_id
    params[:id]
  end

  def page_param
    params[:page] || 1
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def has_more_option(post_count)
     return (post_count > 5)
  end

  def page_counter(details)
    return "#{details.current_page}/#{@details.total_pages}"
  end

end

app/views/admin/payments/index.html.erb
<!--start l-contents-->
<div class="l-container u-clear">
  <!--start l-main-->
  <main class="l-main js-main">
    <div class="l-main-block"></div>

    <h2>
      <br />
      Total Paid Amount: <%= @paid_amount %>
      <br />
      Available Amount : <%= @available_amount %>
    </h2>

    <button type="submit" class="btn btn-primary btn-lg btn-float"> Request and Glorify my Payout</button>


  </main>
  <!--end l-main-->
</div>
<!--end l-contents-->

app/views/admin/posts/_form.html.erb
<label for="image" class="form-title">EYE CATCH IMAGE
  <div class="form-file u-clear">
    <div class="file-name-hldr">
    <% if !@post.new_record? %>
      <%= @post.image_name %>
    <% end %>
    </div>
    <span class="form-file-button">UPLOAD</span>
  </div>
</label>

<%= f.file_field :image, id:"image", class:"input input-image image-uploader" %>

<label for="title" class="form-title">TITLE</label>

<div class="form-body">
  <%= f.input_field :title, required: true, autofocus: true, class:"input input-text", id: "title" %>
</div>

<label for="contents" class="form-title">CONTENTS</label>
<div class="form-textarea">
  <%= f.input_field :contents, required: true, autofocus: true, class:"input input-contents", id: "inquiry", cols:"30", rows:"10" %>
</div>

<div class="form-body">
      <label for="contents" class="form-title">Is Published</label>
     <%= f.select :'other_details[is_published]', ["on","off"], selected: (@post.is_published if !@post.new_record?)  %>
</div>

app/views/admin/posts/_post.html.erb
<li class="archive-item">
  <%= link_to edit_admin_post_path(post), class:"post-article" do %>
    <time class="post-article-date" datetime="<%= post.common_post_date %>"><%= post.display_post_date %> ( <%= post.is_published %> )</time>
    <h1 class="post-article-title"><%= post.title %></h1>
  <% end %>
</li>

app/views/admin/posts/edit.html.erb
<!--start l-contents-->
<div class="l-container u-clear">
  <!--start l-main-->
  <main class="l-main js-main">
    <div class="l-main-block"></div>
    <%= simple_form_for(@post, url: admin_post_path(@post), html:{ class:" form "}) do |f| %>

      <%= render 'form', {f: f }  %>

      <%= render partial: '/layouts/shared/flash_message', locals: { obj: @post } %>

      <label for="submit" class="form-button">
        <div class="button">
          <p class="button-text">Submit</p>
        </div>
      </label>
      <input type="submit" id="submit" class="input input-submit">

      <%= link_to admin_posts_path, class:"form-button" do %>
        <div class="button">
          <p class="button-text">Back</p>
        </div>
      <% end %>
    <% end %>
  </main>
  <!--end l-main-->
</div>
<!--end l-contents-->

app/views/admin/posts/index.html.erb
<!--start l-contents-->
<div class="l-container u-clear">
  <!--start l-main-->
  <main class="l-main js-main">
    <div class="l-main-block"></div>

    <%= link_to new_admin_post_path, class:"l-main-button" do %>
      <div class="button">
        <p class="button-text">New Article</p>
      </div>
    <% end %>

    <ul class="archive archive-admin">
      <%= render partial: "post", collection: @posts %>
    </ul>

  </main>
  <!--end l-main-->
</div>
<!--end l-contents-->

app/views/admin/posts/new.html.erb
<!--start l-contents-->
<div class="l-container u-clear">
  <!--start l-main-->
  <main class="l-main js-main">
    <div class="l-main-block"></div>
    <%= simple_form_for(@post, url: admin_posts_path, html:{ class:" form "}) do |f| %>

      <%= render 'form', {f: f }  %>

      <%= render partial: '/layouts/shared/flash_message', locals: { obj: @post } %>

      <label for="submit" class="form-button">
        <div class="button">
          <p class="button-text">Submit</p>
        </div>
      </label>
      <input type="submit" id="submit" class="input input-submit">
      <%= link_to admin_posts_path, class:"form-button" do %>
        <div class="button">
          <p class="button-text">Back</p>
        </div>
      <% end %>
    <% end %>
  </main>
  <!--end l-main-->
</div>
<!--end l-contents-->

app/views/admin/published_posts/_index.html.erb
<table>
  <%= render partial: "post", collection: @posts %>
</table>

app/views/admin/published_posts/_post.html.erb
<tr class="archive-item">
  <td><time class="post-article-date" datetime="<%= post.common_post_date %>"><%= post.display_post_date %> ( <%= post.is_published %> )</time</td>
  <td><%= post.title %> </td>
  <td><%= link_to edit_admin_post_path(post), class:"post-article" do %>edit<% end %></td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 9]>
<html lang="ja" class="no-js lt-ie9" prefix="og: http://ogp.me/ns#">
  <![endif]-->
  <!--[if gt IE 9]><!-->
  <html lang="ja" class="no-js" prefix="og: http://ogp.me/ns#"><!--<![endif]-->
    <head>
      <meta charset="UTF-8">
      <title>Bligger</title>
      <meta name="description" content="sample text,sample tex">
      <meta name="keywords" content="word1,word2,word3">

      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta property="og:title" content="">
      <meta property="og:description" content="sample text,sample tex">
      <meta property="og:url" content="">
      <meta property="og:site_name" content="">
      <meta property="og:type" content="blog">
      <meta property="fb:admins" content="">
      <meta property="og:image" content="assets/images/common/ogp.png">

      <meta name="apple-mobile-web-app-title" content="">

      <link rel="shortcut icon" href="assets/images/common/favicon.ico">
      <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png">

      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

    <body id="js-body">
      <div id="fb-root"></div>

      <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
      <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

      <input type="hidden" value="./" id="js-base-url">

      <div class="l-wrap js-wrap">

        <%= render partial: "/layouts/shared/header" %>
        <%= render partial: "/layouts/shared/nav" %>

        <%= yield %> <!--render-contents-->

        <%= render partial: "/layouts/shared/footer" %>

      </div>

      <!--javascript ここから-->
      <%= yield :extra_javascripts %>
      <%= javascript_include_tag "footer" %>
      <!--javascript ここまで-->

    </body>
  </html>

app/views/layouts/application_admin.html.erb
<!DOCTYPE html>
<!--[if lt IE 9]>
<html lang="ja" class="no-js lt-ie9" prefix="og: http://ogp.me/ns#">
  <![endif]-->
  <!--[if gt IE 9]><!-->
  <html lang="ja" class="no-js" prefix="og: http://ogp.me/ns#"><!--<![endif]-->
    <head>
      <meta charset="UTF-8">
      <title>Bligger</title>
      <meta name="description" content="sample text,sample tex">
      <meta name="keywords" content="word1,word2,word3">

      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta property="og:title" content="">
      <meta property="og:description" content="sample text,sample tex">
      <meta property="og:url" content="">
      <meta property="og:site_name" content="">
      <meta property="og:type" content="blog">
      <meta property="fb:admins" content="">
      <meta property="og:image" content="assets/images/common/ogp.png">

      <meta name="apple-mobile-web-app-title" content="">

      <link rel="shortcut icon" href="assets/images/common/favicon.ico">
      <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png">

      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

    <body id="js-body">
      <div id="fb-root"></div>

      <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
      <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

      <input type="hidden" value="./" id="js-base-url">

      <div class="l-wrap js-wrap">

        <%= render partial: "/layouts/shared/admin/header" %>

        <%= yield %> <!--render-contents-->

        <%= render partial: "/layouts/shared/admin/footer" %>

      </div>

      <!--javascript ここから-->
      <%= yield :extra_javascripts %>
      <%= javascript_include_tag "footer" %>
      <!--javascript ここまで-->

    </body>
  </html>

app/views/layouts/application_buyer.html.erb
<!DOCTYPE html>
<!--[if lt IE 9]>
<html lang="ja" class="no-js lt-ie9" prefix="og: http://ogp.me/ns#">
  <![endif]-->
  <!--[if gt IE 9]><!-->
  <html lang="ja" class="no-js" prefix="og: http://ogp.me/ns#"><!--<![endif]-->
    <head>
      <meta charset="UTF-8">
      <title>Bligger</title>
      <meta name="description" content="sample text,sample tex">
      <meta name="keywords" content="word1,word2,word3">

      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta property="og:title" content="">
      <meta property="og:description" content="sample text,sample tex">
      <meta property="og:url" content="">
      <meta property="og:site_name" content="">
      <meta property="og:type" content="blog">
      <meta property="fb:admins" content="">
      <meta property="og:image" content="assets/images/common/ogp.png">

      <meta name="apple-mobile-web-app-title" content="">

      <link rel="shortcut icon" href="assets/images/common/favicon.ico">
      <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png">

      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

    <body id="js-body">
      <div id="fb-root"></div>

      <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
      <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

      <input type="hidden" value="./" id="js-base-url">

      <div class="l-wrap js-wrap">

        <%= render partial: "/layouts/shared/admin/header" %>

        <%= yield %> <!--render-contents-->

        <%= render partial: "/layouts/shared/admin/footer" %>

      </div>

      <!--javascript ここから-->
      <%= yield :extra_javascripts %>
      <%= javascript_include_tag "footer" %>
      <!--javascript ここまで-->

    </body>
  </html>

app/views/layouts/shared/_flash_message.html.erb
<% if obj.try(:errors).try(:any?) %>
  <div class="form-title">Error</div>
<% end %>

app/views/layouts/shared/_footer.html.erb
<!--footer ここから-->
<footer class="l-footer ">

  <div class="l-footer-button">
    <a class="page-top js-scroll" href="#js-body">
      <span class="page-top-arrow"></span>
    </a>
  </div>
  <div class="l-footer-copyright">
    <small class="copyright">&copy;copyright</small>
  </div>

</footer>
<!--footer ここまで-->

app/views/layouts/shared/_header.html.erb
<!--start header-->
<header class="l-header js-header">
  <div class="l-header-top u-clear">

    <div class="l-header-logo">
     <%= link_to root_path do %>
       <div class="logo">
         <%= image_tag(asset_path('logo.png'), alt:'BLOG', width: '253px;', height: '28') %>
       </div>
     <% end %>
    </div>

    <div class="l-header-hamburger">
      <a href="#" class="hamburger js-hamburger " >
        <span class="hamburger-item"></span>
        <span class="hamburger-item"></span>
        <span class="hamburger-item"></span>
      </a>
    </div>

  </div>
</header>
<!--end header-->

app/views/layouts/shared/_nav.html.erb
<nav class="nav js-nav">
  <ul class="nav-list">
    <li class="nav-item">
      <%= link_to "TOP", posts_path, class:"nav-link" %>
    </li>

    <li class="nav-item">
      <%= link_to "Login", user_session_path, class:"nav-link" %>
    </li>

    <li class="nav-item">
      <%= link_to "Register", new_user_registration_path, class:"nav-link" %>
      <hr />
    </li>

    <li class="nav-item">
      <%= link_to "Facebook", "https://www.facebook.com/", target: "blank", class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Twitter", "https://twitter.com/", target: "blank", class:"nav-link" %>
    </li>

  </ul>
</nav>

app/views/layouts/shared/admin/_header.html.erb
<!--start header-->
<header class="l-header l-header-admin js-header">
  <div class="l-header-top u-clear">
    <div class="l-header-logo">
     <%= link_to root_path, class:"logo" do %>
         <%= image_tag(asset_path('logo-admin.png'), width:'138px;', height:'28', alt:"BLOG") %>
     <% end %>
    </div>
    <div class="l-header-text">
      <p>
        <% if user_signed_in?  %>
          <%= "Welcome #{(current_user.username)} / #{(current_user.user_type).upcase} / "  %>

          <%= link_to "GloryProfit", admin_payments_path if current_user.influencer? %> /

          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else  %>
          Login
        <% end %>
      </p>
    </div>

  </div>
</header>
<!--end header-->

app/views/posts/_post.html.erb
<li class="archive-item">
  <article class="card">
    <%= link_to post_path(post), class:"card-link" do %>
      <%= (image_tag(asset_path(post.image_url), class:"card-image")) if post.image_url %>
      <div class="card-bottom">
        <h1 class="card-title"><%= post.title %></h1>
        <time class="card-date" datetime="<%= post.common_post_date %>">
          <%= post.display_post_date %>
        </time>
      </div>
    <% end %>
  </article>
</li>

app/views/posts/archive.html.erb
<!--start l-contents-->
<div class="l-container u-clear">
  <!--start l-main-->
  <main class="l-main js-main">
    <div class="l-main-block"></div>

    <div class="page-number">
      Page <span > <%= "#{@posts.current_page}/#{@posts.total_pages}" %></span>
    </div>

    <div class="archive">
      <ul class="archive-list">
        <%= render partial: "post", collection: @posts %>
      </ul>
    </div>

    <%= paginate @posts %>

    </div>
 </main>
 <!--end l-main-->
</div>
<!--end l-contents-->

app/views/posts/index.html.erb
<!--start l-contents-->
<div class="l-container u-clear">

  <!--start l-main-->
  <main class="l-main js-main">
    <div class="l-main-block"></div>
    <div class="archive">
      <ul class="archive-list">
        <%= render partial: "post", collection: @posts %>
      </ul>
    </div>

    <% if has_more_option(@post_count) %>
      <%= link_to archive_posts_path, class:"archive-button" do %>
        <div class="button">
          <p class="button-text">More</p>
        </div>
      <% end %>
    <% end %>

  </main>
  <!--end l-main-->
</div>
<!--end l-contents-->

app/views/posts/show.html.erb
<!--start l-main-->
<main class="l-main js-main">
  <div class="l-main-block"></div>
  <div class="single">
    <%= (image_tag(asset_path(@post.image_url), class:"single-image")) if @post.image_url %>
    <div class="l-container u-clear">
      <h1 class="single-title">
        <%= @post.title %>
      </h1>
      <time class="single-date" datetime="<%= @post.common_post_date %>">
        <%= @post.display_post_date %>
      </time>
      <p class="single-desc">
        <%= @post.contents %>
      </p>
      <div class="single-button">
        <%= link_to root_path do %>
          <div class="button">
            <p class="button-text">Top</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>
<!--end l-main-->